config/routes.rb
Regnum::Application.routes.draw do
  
  match '/' => 'search#index'
  match '/logout' => 'accounts#logout', :as => :logout
  match '/login' => 'accounts#login', :as => :login
  match '/authenticate' => 'accounts#authenticate', :as => :authenticate
  match '/signup' => 'accounts#new', :as => :signup
  match '/mysubmission_show' => 'my_submission#show', :as => :mysubmission
  match '/admin_show' => 'admin#show', :as => :admin
  match '/new_submission' => 'my_submission#new', :as => :new_submission
  match '/create_submission' => 'my_submission#new', :as => :create_submission
  match '/accepted' => 'my_submission#accepted', :as => :accepted
  match '/cladename' => 'my_submission#cladename', :as => :cladename
  match '/save' => 'my_submission#save', :as => :save
  
  match '/faq' => 'application#faq', :as => :faq

  match '/search' => 'search#index', :as => :search
  match '/search/:id' => 'search#show', :as => :show
  match '/search_res' => 'search#search_res', :as => :search_res

  match '/save_submission' => 'my_submission#save_submission', as: :save_submission
  match '/name/:id' => 'cladename#find_name', :as => :name

  match '/my_submission' => 'my_submission#index', :as => :my_submission
  match '/my_submission/new' => 'my_submission#new', :as => :new
  match '/my_submission/template' => 'my_submission#template', :as => :template
  match '/my_submission/add_attachment' => 'my_submission#add_attachment', :as => :add_attachment
  match '/my_submission/view_attachment/:id' => 'my_submission#view_attachment', :as => :view_attachment
  match '/my_submission/remove_attachment/:id' => 'my_submission#remove_attachment', :as => :remove_attachment
  match '/my_submission/delete/:id' => 'my_submission#delete', :as => :delete
  #this one comes last so my_submission method calls can pass
  match '/my_submission/:id' => 'my_submission#show', :as => :show_my_submission  
  match '/templates/load' => 'templates#load', :as => :load_template
  #
  match '/admin' => 'admin#index', :as => :admin
  match '/admin/add_user' => 'admin#add_user', :as => :add_user_admin
  #
  match '/admin/users/:id' => 'admin#edit_user'
  match '/admin/update_user/:id' => 'admin#update_user', :as => :update_user
  #
  match '/phenotypes' => 'phenotypes#index', :as => :phenotypes
  match '/phenotypes/create' => 'phenotypes#create' 
  match '/phenotypes/import_ontologies' => 'phenotypes#import_ontologies'
  #match '/phenotypes/new/:state_id' => 'phenotypes#new'
  match '/phenotypes/new' => 'phenotypes#new'
  match '/phenotypes/get_form_fields' => 'phenotypes#get_form_fields'
  match '/characters/new' => 'phenotypes#new_character'
  match '/characters/create_character' => 'phenotypes#create_character'
  match '/characters/destroy_character' => 'phenotypes#destroy_character'
  match '/characters/destroy_state' => 'phenotypes#destroy_state'
  match '/characters/destroy_phenotype' => 'phenotypes#destroy_phenotype'
  match '/characters/:character_id/states/new' => 'phenotypes#new_state'
  match '/characters/:character_id/states' => 'phenotypes#create_state' , :via => [:post]
  match '/ontologies/auto_complete_terms' => 'ontologies#auto_complete_terms'
  resources :accounts
  resources :submissions

  #match '/:controller(/:action(/:id))'
end

app/models/submission.rb
class Submission < ActiveRecord::Base

  self.table_name = "submissions"
  self.inheritance_column = false

  attr_accessible :name, :authors, :comments, :establish, :preexisting, :type, :specifiers, :citations
  attr_accessor :status_comments #editors comments for status changes

  has_many :submission_citation_attachments

  belongs_to :status
  has_many :status_changes
  belongs_to :user, :foreign_key => :submitted_by
  
  #scope :submitted, where("status_id <> 4")
  #scope :approved, where("status_id = 4")
  @current_time = Time.now

  before_create lambda{ self.status_id = 1 }
  before_create :check_serialized

  after_find :check_serialized
  after_find lambda{ @current_status = self.status_id }

  #citation
  before_update lambda{ self.updated_at = @current_time }
  before_update :check_status_change
  #citations and specifiers are stored as hashes
  #also conveniently makes all the fields searchable on a single column
  serialize :citations, Hash
  serialize :specifiers, Hash
  
  scope :opt_in, where(:establish => true)
  scope :opt_out, where(:establish => false)
  #scope :approved, where(:status_id => Status.where(:status => 'approved').first.id)
  
  def temp_id
    #registration number for users
    #number is based on table primary key just with padding up to 9 numbers
    "#{self.id.to_s.rjust(10,'0')}"
  end

  def current_status_comments
    stat = StatusChange.find_by_submission_id_and_status_id_and_changed_at(self.id, self.status_id, self.updated_at)
    if stat == nil
      ''
    else
      stat.comments
    end
  end
  
  def submitted_by_user?(current_user_id)
    self.submitted_by == current_user_id
  end

  private

  # sets empty serialized fields
  def check_serialized
    ####remember you can assign numerics as keys in ruby a hash
    cits = {'preexisting' => {0=>{}}, 'description' => {0=>{}}, 'phylogeny' => {0=>{}}, 'primary-phylogeny' => {0=>{}}}
    specs = {0=>{}}
    ####
    if self.citations == nil
      self.citations = cits
    else
      cits.each{|k,v| self.citations[k]=v unless self.citations.has_key?(k)}
    end
    ####
    if self.specifiers == nil
      self.specifiers = specs
    end
  end

  # create new status change record on status change
  def check_status_change
    if self.status_id != @current_status
      sc = StatusChange.new
      sc.submission_id = self.id
      sc.status_id = self.status_id
      sc.changed_at = @current_time 
      sc.comments = status_comments
      sc.save
      #give sub a global id if approved
      if self.status.eq?('approved')
        self.guid = generate_guid(@current_time)
      end
    end
  end
  
  def generate_guid(time=nil)
    UUIDTools::UUID.timestamp_create(time).to_s
  end
  
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  before_filter :requires_a_editor_or_admin

  def index
    @subs = submissions_for_editor(params)
    if request.xhr?
      render :partial => 'submissions/submissions_table' , :layout => false
    end
  end

  def show
    @sub = Submission.find(params[:id])
    @stats = StatusChange.where(:submission_id => params[:id]).order('changed_at DESC')

    #if request.xhr?
      render :show, :layout => false
    #end     
  end

  def destroy
    Submission.delete(params[:id])
    SubmissionCitationAttachment.delete_all(["submission_id = ?", params[:id]])
    #request.xhr? ? head :ok : redirect_to :action => :index
    @subs = submissions_for_editor(params)
    if request.xhr?
      render :partial => 'submissions/submissions_table' , :layout => false
    else
      redirect_to :action => :index
    end
  end
  

  def update

    sub = Submission.find(params[:id])
    sub.status_id = params[:status]
    sub.status_comments= params[:editor_comments]
    sub.save
    #send email
    #StatusMailer.status_change(current_user, sub).deliver
    if request.xhr?
      index
    else
      redirect_to :action => :index
    end
  end

  private
  #gets right set of subs depending of type of editor/admin
  def submissions_for_editor(params)
    params[:term] ||= ''
    params[:page] ||= '1'
    params[:order] ||= 'name'
    params[:dir] ||= 'up'
    dir = params[:dir] == 'up' ? 'ASC' : 'DESC'
    subs = if current_user.is_admin?
      Submission.where("name LIKE ?", "#{params[:term]}%") #admin sees all :)
    elsif current_user.is_reviewer?
      Submission.where("status_id > ? AND name LIKE ?", Status.find_by_status('unsubmitted').id, "#{params[:term]}%")
    elsif current_user.is_opt_out_reviewer?
      Submission.opt_out.where("status_id > ? AND name LIKE ?", Status.find_by_status('unsubmitted').id, "#{params[:term]}%")
    elsif current_user.is_opt_in_reviewer?
      Submission.opt_in.where("status_id > ? AND name LIKE ?", Status.find_by_status('unsubmitted').id, "#{params[:term]}%") 
    end .order("#{params[:order]} #{dir}").paginate(:page => params[:page], :per_page => 12)
    return subs
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  

  
end

app/views/submissions/_submissions_table.html.haml
.sortable-table-div
  %table#user_submissions_table.sortable-table
    %tr.sortable-table-header-row
      %th.sortable.table-header-link=table_sort_header('name')
      %th.sortable.table-header-link=table_sort_header('status_id','status')
      %th.sortable.table-header-link=table_sort_header('submitted_by') 
      %th{:colspan => 3}
    %tbody
      -@subs.each do |sub|
        %tr{:class => cycle('odd-row','even-row'), :id => sub.id, :title => "click to open submission"  }
          %td= sub.name
          %td= sub.status.status
          %td{ :style => 'width:180px'}= sub.user.last_name + ', ' + sub.user.first_name
          %td{ :style => 'width:40px'}
            =form_for sub, :url => submission_path(sub.id), :html => {:method => :get } do |s|
              %input.submit_button{:type => 'submit', :value => 'review'} 
          -if current_user.is_admin? 
            %td{:style => 'width:40px'}
              =form_for sub, :url => my_submission_path + '/' + sub.id.to_s, :html => {:method => :get } do |s|
                %input.submit_button{:type => 'submit', :value => 'edit'} 
          %td{ :style => 'width:40px'}
            =form_for sub, :url => submission_path(sub.id), :html => {:method => :delete } do |s|
              %input.submit_button{:type => 'submit', :value => 'delete', :title => 'click to delete'}
      %tr
        %td{:colspan => 5, :style => 'text-align:center;padding:1px;border:none;'}
          =will_paginate @subs, renderer: RemoteLinkRenderer,:params => {:controller => :submissions, :action => nil}
      %tr
        %td{:colspan => 5, :style => 'text-align:center;padding:1px;border:none;'}
          =page_entries_info @subs, {:model => 'clade names'}

app/views/submissions/index.html.haml
.content_box{:style => 'margin:20px auto;display:block;max-width:390px;'}
  %form{:action => '/submissions', :method => :get }
    %table{:style => 'width:100%'}
      %tr
        %td.bold Submissions Search: 
      %tr
        %td{:style => 'text-align:left;'} 
          %input{:type => :text, :size => 25, :name => 'term', :style => 'height:27px;'}
        %td{:style => 'text-align:right;'}
          %input{:type => :submit, :value => 'search', :id => 'search-button', :class => 'button'}
#submissions_table_div.sortable-table-holder
  = render :partial => 'submissions/submissions_table'

app/views/submissions/show.html.haml
%div{:style => 'margin:10px 0px;float:left;clear:both;width:100%;'}
  =render :partial => 'shared/status_change_list'
.submission-holder{:style => 'float:left;clear:both;'}
  =render :partial => 'shared/cladename_view'
.editor-box
  -form_for @sub, :url => '/submissions/'+@sub.id.to_s, :method => :put do |s|
    %table
      %tr
        %td.name Status:
        %td{:style => 'text-align:right;'}
          %input{:type => 'submit', :value => 'Save', :id => 'sub_save_button'}
      %tr
        %td
          %select{:name => 'status'}
            = options_from_collection_for_select Status.all, :status_id, :status, @sub.status_id
      %tr
        %td.name{:colspan => '2' } Editor Comments:
      %tr
        %td{:colspan => '2'}
          %textarea{ :name => 'editor_comments', :rows => 5, :cols => 87 }